[book]
title = "Uazú blog"
author = "Jim Peters"
description = "Articles on Uazú crates"

[rust]
edition = "2018"

[build]
build-dir = "../../blog"
create-missing = false

[output.html]
default-theme = "rust"
site-url = "/blog/"

[output.html.fold]
enable = true
